config/routes.rb
Draww::Application.routes.draw do
  
  root :to => 'posts#index'
  
  # User Management
  resources :authentications, :users, :user_sessions

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  get "relationship/create"
  get "relationship/destroy"

  match 'login', :to => 'user_sessions#new', :as => :login
  match 'logout', :to => 'user_sessions#destroy', :as => :logout
  
  # Posts Display
  match '/tags/:tag_name' => 'posts#index', :as => :tag_name
  match '/u/:username' => "Users#show", :as => :name_user
  match '/posts/new/:id' => 'Posts#new_child', :as => :new_child_post

  match '/posts/sweep_hotness_cache' => 'posts#sweep_hotness_cache'
  
  resources :posts do
    resources :comments
    get 'page/:page', :action => :index, :on => :collection
  end

  # Voting
  match '/posts/:id/vote' => 'posts#vote', :as => :vote

end

app/models/user.rb
class User < ActiveRecord::Base
  
  # TODO: Add Website / Gravatar Icon / About you fields

  attr_accessor :created_from_oauth

  acts_as_authentic do |c|
    c.merge_validates_confirmation_of_password_field_options({:unless => :created_from_oauth})
    c.merge_validates_length_of_password_field_options({:unless => :created_from_oauth})
    c.merge_validates_length_of_password_confirmation_field_options({:unless => :created_from_oauth})
    c.merge_validates_length_of_email_field_options({:unless => :created_from_oauth})
    c.merge_validates_format_of_email_field_options({:unless => :created_from_oauth})
    c.merge_validates_uniqueness_of_email_field_options({:unless => :created_from_oauth})
  end
  
  
  has_many :posts
  has_many :comments
  has_many :votes
  has_many :liked_posts, :through => :votes
  has_many :authentications, :dependent => :destroy
    
  def author_score
    posts.inject(1){|s,p| s += p.votes_score}
  end
  
  def casting_power # points of posts created
    author_score # should perhaps be a % of all author scores or post scores or some such...
  end
  
  def vote(post)
    votes.build(:post => post)
  end

  def vote!(post)
    votes.create!(:post => post)
  end
  
  def self.create_from_hash(hash)
    # puts "CREATING USER FROM HASH".log_red
    # user = User.new(:username => hash['info']['name'].scan(/[a-zA-Z0-9_]/).to_s.downcase, :email => "testing_tw@test.loc", :created_from_oauth => true )
    user = User.new(:username => hash['info']['name'].scan(/[a-zA-Z0-9_]/).to_s.downcase, :created_from_oauth => true )
    user.save! #create the user without performing validations. This is because most of the fields are not set.
    user.reset_persistence_token! #set persistence_token else sessions will not be created
    user
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if(params[:username])
      @user = User.where(:username => params[:username]).first
    else
      @user = User.find(params[:id])
    end
    
    respond_to do |format|
      if @user    
        @posts = @user.posts.order("created_at DESC").page params[:page]
        format.html # show.html.erb
        format.json { render :json => @user }
      else
        format.html { render :action=> 'not_found' }
        # redirect_to :action => 'not_found'  # TODO: can this be an action so we don't end up with duplicate content
      end
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @authentications = @user.authentications if current_user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to name_user_path(current_user.username), :notice => 'Registration successfull.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" } # TODO_HELP: How do I redirect this to 'user_sessions/new' without losing validation errors? user_session/new and user/new now occupy the same view (combined login and signup). Am I even doing that the right way?
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, :html => { :multipart => true, :class => 'form-horizontal' }) do |f| %>
  <%= render "shared/error_messages", :target => @user %>
  <fieldset>
    <legend>Create a New Account:</legend>
    <% unless action_name == 'edit' %>
      <div class="control-group">
	<%= f.label :username, :class => 'control-label' %>
	<div class="controls">
	  <%= f.text_field :username, :class => 'span4' %>        
	</div>
      </div>
    <% end %>
    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'span4' %>        
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :password, :class => 'span4' %>        
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password_confirmation, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :password_confirmation, :class => 'span4' %>        
      </div>
    </div>
    <div class="form-actions">
      <%= f.submit "Login", :class => 'btn btn-primary' %>
    </div>
  </fieldset>	
<% end %>

app/views/users/edit.html.erb
<h1>Your Preferences</h1>

<%= render 'form' %>

<h2>Auth</h2>

<%= render 'authentications/auth' %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>

    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
TODO: Delete this? - Shouldn't be used now there's a unified login/signup view

<h1 class="big">Sign up free!</h1>
<div class="social_connect">
	<h4>Connect using your favorite social networking service:</h4>
	<%= render 'authentications/auth' %>
</div>
<div class="local_signup">
	<h4>...or enter your details below:</h4>
	<div class="form">
		<%= render 'form' %>
	</div>
</div>

app/views/users/not_found.html.erb
<p>
	Sorry, that user doesn't exist.
</p>

app/views/users/show.html.erb
<h1><%= @user == current_user ? "Your" : @user.username.capitalize+"'s" %> Images</h1>
<%# TODO: Wouldn't it be nice if there was a "follow user" button here %>
<%# https://github.com/tcocca/acts_as_follower/ perhaps? %>

<% if @user.posts.count > 0 %>
	<%= render '/posts/list' %>
<% elsif @user == current_user %>
	<h2>Thanks for registering! Why don't you <%= link_to 'post something', new_post_path %> or looks at some fucking stuff? Draww works in some way or another.<br /><br /> TODO: Make this message more encouraging!</h2>
<% else %>
	<p><%= @user.username.capitalize %> hasn't posted anything yet</p>
<% end %>
<p>
  <strong>Reputation: </strong><%= @user.author_score %>
  The score you have received from the images you've posted.  This currently gives you a casting power of <%= @user.casting_power %> for your votes.
</p>

<%# link_to 'Edit', edit_user_path(@user) %>
<%= link_to 'Back', users_path %>