config/routes.rb
Draww::Application.routes.draw do
  
  root :to => 'posts#index'
  
  # User Management
  resources :authentications, :users, :user_sessions

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  get "relationship/create"
  get "relationship/destroy"

  match 'login', :to => 'user_sessions#new', :as => :login
  match 'logout', :to => 'user_sessions#destroy', :as => :logout
  
  # Posts Display
  match '/tags/:tag_name' => 'posts#index', :as => :tag_name
  match '/u/:username' => "Users#show", :as => :name_user
  match '/posts/new/:id' => 'Posts#new_child', :as => :new_child_post

  match '/posts/sweep_hotness_cache' => 'posts#sweep_hotness_cache'
  
  resources :posts do
    resources :comments
    get 'page/:page', :action => :index, :on => :collection
  end

  # Voting
  match '/posts/:id/vote' => 'posts#vote', :as => :vote

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  attr_accessor :attachment64
  before_validation :save_attachment64
  before_save :default_values
  # paginates_per 10 < set in config/initializers/kaminari_config
 
  # Allow attributes to be set via mass assignment, eg.
  # Post.new(:title => 'Whatever', :description=> 'Something)
  # Needed for new security in Rails 3.2:
  # http://stackoverflow.com/questions/10050797/rails-error-cant-mass-assign-protected-attributes
  
  attr_accessible :title, :description, :tag_names, :attachment64, :photo 

  # Paperclip
  # All photos should be 3 to 2 aspect
  has_attached_file :photo,
    :styles => {
      :thumb=>    ["170x170>", :jpg],
      }
      
  validates :title, 
    :length => { :minimum => 2, :maximum => 40, :message => "Sorry, title too long or too short" },
    :presence => {:message => "Title can't be blank" }
  validates_attachment_presence :photo
  # validates_attachment_size :photo, :less_than => 1.megabytes

  has_many :comments, :dependent => :destroy
  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings
  attr_writer :tag_names
  after_save :assign_tags
  belongs_to :user

  has_many :votes
  
  has_many :relationships, :dependent => :destroy
  has_many :parents, :through => :relationships
  has_many :inverse_relationships, :class_name => "Relationship", :foreign_key => "relation_id"
  has_many :children, :through => :inverse_relationships, :source => :post
  
  private
  def save_attachment64
    if self.attachment64
      require Rails.root.join('lib', 'datafy.rb')
      tmp_uri = "tmp/"+friendly_name(self.title)+".jpg"
      puts "Friendly name = "+tmp_uri
      File.open(tmp_uri, "wb") { |f| f.write(Datafy::decode_data_uri(attachment64)[0]) }  
      self.photo = File.open(tmp_uri, "r")
    end
  end

  def friendly_name(str)
    s = str.encode('utf-8')
    s.downcase!
    s.gsub!(/'/, '')
    s.gsub!(/[^A-Za-z0-9]+/, ' ')
    s.strip!
    s.gsub!(/\ +/, '-')
    return s
  end
  
  # Ranking
  def default_values
    self.upvote = 1 unless self.upvote
    self.downvote = 0 unless self.downvote
    self.rank = 1 unless self.rank
  end
    
  # Tagging
  
  public
  
  def tag_names
    @tag_names || tags.map(&:name).join(' ') #NB: acts_as_taggable_on does a lot of this for you!
  end
  
  # Ranking System
  
  def votes_count
    self.votes.count
  end
  
  def votes_score
    votes.inject(0){|s,v| s += v.points || 0} 
  end

  def votes_hotness
    cached_hotness || calculate_votes_hotness
  end
  
  def calculate_votes_hotness
    votes.inject(0){|s,v| s += v.heat || 0} 
  end

  private

  def assign_tags
    if @tag_names
      self.tags = @tag_names.split(/\s+/).map do |name|
        Tag.find_or_create_by_name(name)
      end
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :require_user, :only => [:new, :create, :update, :edit, :destroy, :vote]
  respond_to :html, :json, :js

  # NOTE: This could be simplified with the following.
  # from http://railscasts.com/episodes/302-in-place-editing
  #
  # respond_to :html, :json
  # def update
  #   @user = User.find(params[:id])
  #   @user.update_attributes(params[:user])
  #   respond_with @user
  # end
  
  # GET /posts
  # GET /posts.json
  def index
    if params[:tag_name]
      # find posts by tag: /tags/tagname
      @posts = Tag.find_by_name(params[:tag_name]).posts.order("created_at DESC").page params[:page]
    else
      # find all posts
      @posts = Post.order("cached_hotness DESC").page params[:page]
    end

    respond_with(@posts, :layout => !request.xhr?)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    # sleep 2
    @post = Post.find(params[:id])
    @comment = @post.comments.build

    respond_with(@post, :layout => !request.xhr?)
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    # sleep 2
    @post = Post.new

    respond_with(@post, :layout => !request.xhr?)
  end
  
  def new_child
    @post = Post.new
    @post_parent = Post.find(params[:id])

    render("new", :layout => !request.xhr?)
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    relation_id = params[:post][:relation_id]
    params[:post].delete(:relation_id) if relation_id

    @post = Post.new(params[:post])
    # If it's new_child, build relationship to parent
    @post.relationships.build(:relation_id => relation_id) if relation_id
    
    if @post.save
      current_user.posts << @post
       flash[:notice] = 'Post was successfully created.'
    end

    respond_with(@post, :layout => !request.xhr? )
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
 
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, :notice => 'Post was successfully updated.' }
        format.json { respond_with_bip(@post) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@post) }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_with(@post, :location => posts_url)
  end
  
  def vote
    @post = Post.find(params[:id])    
    logger.info "#{current_user.username } voting for #{@post.title}"
    vote = current_user.vote(@post)
    if vote.valid?
      flash[:notice] = "You voted for #{@post.title}!\nOn behalf of #{@post.user.username}, thanks!"
      vote.save!
    elsif vote.errors.messages.has_key?(:user_id)
      flash[:errors] = "You've already voted for #{@post.title}!"  # TODO_HELP: This just errors out ActiveRecord::RecordInvalid at the moment. Why is the validation error not being caught with this flash
    else
      flash[:errors] = "Couldn't vote sorry!"
    end
    redirect_to request.referer
    #respond_with(@post)
    #respond_to do |format|
    #  if current_user.vote!(@post).save
    #    format.html { render :upvote, :notice => "You voted for #{@post.title}!\nOn behalf of #{@post.user.username}, thanks!" }
    #    format.json { head :ok }
    #  else
    #    format.html { render :upvote, :errors => @post.errors }
    #    format.json { render :json => @post.errors, :status => :unprocessable_entity }
    #  end
    #end
  end
  
  def sweep_hotness_cache
    t = Time.now
    logger.info "Starting Cache Sweep..."
    Post.all.each do |p|
      p.cached_hotness = p.calculate_votes_hotness
      p.save! # where will errors get raised?
    end
    logger.info "Cache Swept (in #{((Time.now-t)/6).to_i/10.0} minutes)"
    flash[:notice] = "Cache Swept"
    redirect_to :action => :index
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
  def join_tags(post)
    post.tags.map { |t| t.name }.join(", ")
  end
  
  def tag_links(post)
    links = ''
    post.tags.map { |t| links += link_to( t.name, tag_name_path(t.name), :class => "tag") }
    return links.html_safe
  end
    
  def belongs_to_current_user(post)
    if post.user == current_user 
      return true
    else
      return false
    end
  end
  
end

app/views/posts/_form.html.erb
<% @post.tags.build %>
<%= form_for(@post,:html => { :multipart => true }, :remote => true) do |f| %>
    <%= render "shared/error_messages", :target => @post %>

    <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, :placeholder => 'Untitled' %>
    </div>
    <div class="field">
        <%= f.label :tag_names %>
        <%= f.text_field :tag_names %>
    </div>
    <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description, :rows => 3 %>
    </div>

    <%= f.hidden_field :attachment64 %>
    <%= f.hidden_field :relation_id, :value => @post_parent.id if @post_parent %>
    <div class="submit">
        <%= f.button "Post This" %>
    </div>
<% end %>

app/views/posts/_list.html.erb
<div id="index">
<% @posts.each do |post| %><div class="thumb" id="post_<%= post.id %>">
    <% if post.photo.exists? then %>
      <%= image_tag(post.photo.url(:thumb), :alt => post.title, :class => 'pic') %>
	<%# render :partial => 'posts/ranking', :locals => { :post => post } %>
        <div class="overlay">
            <div class="actions">
                <%= link_to( content_tag("span", "Inspect"), post, :class => "inspect" ) %>
                <%= link_to( content_tag("span", "Vote"), vote_path(post), :class => "vote" ) %>
            </div>
        </div>
    <% else %>
      Error! Post has no photo.
    <% end %>
  </div><% end %>
</div>
<%= paginate @posts %>

app/views/posts/_ranking.html.erb
<div class="ranking">
	<%# "#{post.votes_count} votes worth #{post.votes_score} reputation" %>
	<%- post.upvote - post.downvote %>
	<%= link_to content_tag(:span, "Vote Up"), vote_path(post), :class => 'vote_up' %>
	<%= link_to post.votes_count, post, :class => 'vote_count' %>
        <%= link_to content_tag(:span, "Vote Down"), vote_path(post), :class => 'vote_down' %><%# TODO: Get Vote down working %>
</div>

app/views/posts/create.js.erb
console.log('create.js.erb loaded');
var el = $('.ajax_message');

<% if @post.errors.any? %>

	// Create a list of errors
	var errors = $('<ul />');

	<% @post.errors.full_messages.each do |error| %>
		errors.append('<li><%= escape_javascript( error ) %></li>');
	<% end %>

	// Display errors on form
	el.html(errors);

<% else %>
	
	console.log("no errors");
	//el.html('<%= escape_javascript(flash.discard(:notice)) %>');
	window.location.href='<%= url_for @post %>';
	
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>
<%# TODO: Pretty sure we're not going to need this view any more now we have BIP editing 
  - child posts take its place %>
<% content_for :head do %>
<script type="text/javascript">
	$(document).ready(function(){
		// see processingReady()
		pjsReadyFn['load_image_for_edit'] = function() {
			loadRemoteImage('<%= @post.photo.url(:medium) if @post.photo.exists? %>');
		}
	});
</script>
<% end %>
<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render 'list' %>

app/views/posts/new.html.erb
<canvas id="pjs_canvas" tabindex="0">
    <p>Sorry, you should really upgrade your browser.</p>
</canvas>
<div class="actions">
    <div class="tool test1" data-tool-src="/assets/test1.pjs">Test 1</div>
    <div class="tool test2" data-tool-src="/assets/test2.pjs">Test 2</div>
</div>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="full_image">
    <% if @post.photo.exists? then %>
        <%= image_tag @post.photo.url(:original), :class => 'medium' %><%# TODO: Should show full screen on click %>
    <% else %>
        <p>Error: No photo.</p>
    <% end %>
</div>
<div class="actions">
    <%= link_to content_tag(:span, @post.votes_count), vote_path(@post), :class => 'vote' %>
    <%= link_to content_tag(:span, 'Edit'), new_child_post_path(@post), :class => 'edit', :rel => 'nofollow' %>
    <a href="#" class="comments"><span>Comments</span></a>
</div>
<div class="title">
    <h1>
        <%= best_in_place_if @post.user == current_user, @post, :title %>
        <span class="by">by <%= link_to @post.user.username, name_user_path(@post.user.username) %></span>
    </h1>
</div>
<!--
<div class="row">
  <div class="span8">
    <div class="posts-show-header">
	<%= render :partial => 'ranking', :locals => {:post => @post} %><%# TODO: Show which users voted %>
	<h1>
          <%= best_in_place_if @post.user == current_user, @post, :title %>
          <span class="by">by <%= link_to @post.user.username, name_user_path(@post.user.username) %></span>
        </h1>
    </div>

</div>
<div class="span4">
  	<div class="actions">
		<%= link_to content_tag(:span, 'Draww on this image'), new_child_post_path(@post), :class => 'btn', :rel => 'nofollow' %>
		<% if belongs_to_current_user(@post) %>
			<%= link_to content_tag(:span, 'Delete'), @post, :class => 'btn btn-danger', :confirm => 'Are you sure?', :method => :delete %>
		<% end %>
	</div>
	<p>
	  <h3>Description:</h3>
	  <%= best_in_place_if @post.user == current_user, @post, :description, :type => :textarea %>
	</p>

	<p>
	  <h3>Tags:</h3>
	  <%= tag_links(@post) %>
		<%# TODO: find a way to get in-place tag add/delete %>
	</p>

	<h3>Comments</h3>
	<div id="comments">
		<%= render @post.comments - [@comment] %>
	</div>

	<h3>Add a comment:</h3>
	<%= form_for([@post, @comment], :remote => true) do |f| %>
		<%= render "shared/error_messages", :target => @comment %>
		<%= f.text_area :body, :cols => 35, :rows => 6, :class => 'span4' %>
	    <%= f.submit %>
	<% end %>
	
        <% unless @post.parents.empty? and @post.inverse_relationships.empty? %>
          <ul class="thumbnails">          
            <% for parent in @post.parents %>
              <li class="span2">
                <%= link_to(image_tag(parent.photo(:thumb))+content_tag(:h4, 'Parent'), parent, :class => 'thumbnail parent') %>
              </li>
            <% end %>
            <% for relationship in @post.inverse_relationships %>
              <li class="span2">
                <%= link_to(image_tag(relationship.post.photo(:thumb))+content_tag(:h4, 'Child'), relationship.post, :class => 'thumbnail child') %>
              </li>
            <% end %>
          </ul>
      <% end %>
  </div>
</div>
<%# link_to 'Edit', edit_post_path(@post) %>
-->