config/routes.rb
Draww::Application.routes.draw do
  
  root :to => 'posts#index'
  
  # User Management
  resources :authentications, :users, :user_sessions

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  get "relationship/create"
  get "relationship/destroy"

  match 'login', :to => 'user_sessions#new', :as => :login
  match 'logout', :to => 'user_sessions#destroy', :as => :logout
  
  # Posts Display
  match '/tags/:tag_name' => 'posts#index', :as => :tag_name
  match '/u/:username' => "Users#show", :as => :name_user
  match '/posts/new/:id' => 'Posts#new_child', :as => :new_child_post

  match '/posts/sweep_hotness_cache' => 'posts#sweep_hotness_cache'
  
  resources :posts do
    resources :comments
    get 'page/:page', :action => :index, :on => :collection
  end

  # Voting
  match '/posts/:id/vote' => 'posts#vote', :as => :vote

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  def persisted?
    false
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  # GET /user_sessions/new
  # GET /user_sessions/new.xml
  def new
    @user_session = UserSession.new
    @user = User.new  # for new user signup form

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user_session }
    end
  end

  # POST /user_sessions
  # POST /user_sessions.xml
  def create
    @user_session = UserSession.new(params[:user_session])
    @user = User.new  # for new user signup form

    respond_to do |format|
      if @user_session.save
        format.html { redirect_to(name_user_path(@user_session.username), :notice => 'Login Successful') }
        format.xml  { render :xml => @user_session, :status => :created, :location => @user_session }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user_session.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.xml
  def destroy
    @user_session = UserSession.find
    @user_session.destroy

    respond_to do |format|
      format.html { redirect_to(:root, :notice => 'Goodbye!') }
      format.xml  { head :ok }
    end
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_for( @user_session, :html => { :class => 'form-horizontal' } ) do |f| %>
  <%= render "shared/error_messages", :target => @user_session %>
  <fieldset>
    <legend>With an Existing Account</legend>
    <div class="control-group">
      <%= f.label :username, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :username, :class => 'span4' %>        
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password, :class => 'span4' %>        
      </div>
    </div>
    <div class="form-actions">
      <%= f.submit "Login", :class => 'btn btn-primary' %>
      <%# TODO: Use <button> instead of <submit> for forms (better for bootstrap)
      http://stackoverflow.com/questions/6214548/how-to-implements-a-button-tag-to-form-for-helper %>
    </div>
  </fieldset>
<% end %>

app/views/user_sessions/edit.html.erb
<h1>Editing user_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_session %> |
<%= link_to 'Back', user_sessions_path %>

app/views/user_sessions/index.html.erb
<h1>Listing user_sessions</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_sessions.each do |user_session| %>
  <tr>
    <td><%= user_session.username %></td>
    <td><%= user_session.password %></td>
    <td><%= link_to 'Show', user_session %></td>
    <td><%= link_to 'Edit', edit_user_session_path(user_session) %></td>
    <td><%= link_to 'Destroy', user_session, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User session', new_user_session_path %>

app/views/user_sessions/new.html.erb
<h1>Login / Sign up</h1>
<div class="row">
  <div class="span6">
    <%= render 'form' %>
    <h3>Using Social Media:</h3>
    <%= render 'authentications/auth' %>
  </div>
  <div class="span6">
    <%= render 'users/form' %>
  </div>
</div>

app/views/user_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user_session.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user_session.password %>
</p>


<%= link_to 'Edit', edit_user_session_path(@user_session) %> |
<%= link_to 'Back', user_sessions_path %>