config/routes.rb
Draww::Application.routes.draw do
  
  root :to => 'posts#index'
  
  # User Management
  resources :authentications, :users, :user_sessions

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  get "relationship/create"
  get "relationship/destroy"

  match 'login', :to => 'user_sessions#new', :as => :login
  match 'logout', :to => 'user_sessions#destroy', :as => :logout
  
  # Posts Display
  match '/tags/:tag_name' => 'posts#index', :as => :tag_name
  match '/u/:username' => "Users#show", :as => :name_user
  match '/posts/new/:id' => 'Posts#new_child', :as => :new_child_post

  match '/posts/sweep_hotness_cache' => 'posts#sweep_hotness_cache'
  
  resources :posts do
    resources :comments
    get 'page/:page', :action => :index, :on => :collection
  end

  # Voting
  match '/posts/:id/vote' => 'posts#vote', :as => :vote

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Draww</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= yield :head %>
</head>
<body class="<%= controller_name %> <%= action_name %>">

<div id="navbar">
  <div class="inner">
  <%= link_to image_tag("draww.png", :alt => "Draww"), root_path, :class => 'brand' %>
    <ul class="actions">
      <% if current_user %>
        <li class="new"><%= link_to "New", new_post_path %></li>
        <li class="user dropdown">
          <a href="#"><%= current_user.username %></a>
          <ul>
            <li><%= link_to "My Images", name_user_path(current_user.username) %></li>
            <li class="user"><%= link_to "My Profile", edit_user_path(current_user.id) %></li>
            <li class="logout"><%= link_to "Logout", :logout %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Login / Sign up", login_path %></li>
      <% end %>
    </ul>
  </div>
</div>
<div role="main" id="container">
    <%= render 'shared/flashes' %>
    
    <% if request.fullpath == "/" and !current_user %>
    <div class="hero-unit">
        <h1>Draww is a community where people share and collaborate with images.</h1>
	<h4>Upload your own, alter them, and vote for the best. <%= link_to 'Get started now!', new_user_path %></h4>
	<%= link_to content_tag(:span, "Sign Up"), login_path, :class => 'signup_big' %>
    </div>
    <% end %>

    <%= yield %>
    <footer>
        <div class="license">
            <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/">
                <img alt="Creative Commons License" src="/images/cc.png" />
            </a>
            Except where otherwise noted, <span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/StillImage" rel="dct:type">content</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-ShareAlike 3.0 Unported License</a>.
        </div>
    </footer>
</div>
<div class="preload">
    <div class="vote"></div>
    <div class="spinner"></div>
</div>
</body>
</html>